Develop
madromk/java-explore-with-me pull request #1
Opened 2022-10-31 14:47 UTC by madromk

2022-11-02 06:55 UTC, Frilock requested changes
Доброе утро, оставил пару комментариев к работе, жду новую итерацию

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/category/controller/AdminCategoryController.java
> +    @ExceptionHandler
Может быть обработку ошибок в отдельный handler вынести?

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/category/model/Category.java
> +@Data
А Вам и Data и Builder нужны для сущностей?

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/category/repository/CategoryRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.
Проверьте в других местах

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/category/service/CategoryService.java
> +@Slf4j
По моему лишняя аннотация, не вижу использования логгера

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/client/ViewStats.java
> +@Data
А Вам и Data и билдер нужны?

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/client/base/BaseClient.java
> +            if (parameters != null) {
Данную конструкцию можно упростить с использованием тернарного оператора

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/compilation/repository/CompilationEventRepository.java
> +    @Transactional
Тоже нет смысла в таких аннотациях на интерфейсе. Нужно чтоб она была на методе реализации

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/compilation/service/CompilationService.java
> +package ru.practicum.explore_with_me.compilation.service;
По названию пакета комментарий, вообще лучше обходится без символов _. Пакеты стараются называть только строчными буквами

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/compilation/service/CompilationService.java
> +        System.out.println(compilationDb);
Использование System.out в веб приложениях не очень хорошая практика. Либо уберите это либо поменяйте на логгер

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/compilation/service/CompilationService.java
> +        Optional<Compilation> compilationOptional = compilationRepository.findById(compId);
Методы репозитория можно переделать на использование Optional. Тогда тут можно было использовать конструкцию compilationRepository.findById(compId).orElseThrow(...)

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/compilation/service/CompilationService.java
> +@Slf4j
Не вижу использования данной аннотации в коде класса

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/model/Event.java
> +    @ManyToOne()
Скобки не нужны

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +public class EventService implements PageTool {
Не знаю говорили Вам или нет, но как вариант, можете в IDEA установить плагин sonarlint - статический анализатор кода. Покажет ряд хороших практик и возможных проблемных мест

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +        if (eventDb.getState().equals(EventState.PENDING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее
Проверьте в других местах

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +        if (text.isBlank()) {
Я так понимаю, что text может быть null. Тогда вы получите NPE. Лучше такие проверки делать с использование утилиты от apache common 3 - StringUtils.isBlank

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +                case "EVENT_DATE":
У Вас вроде для этих значений енам есть. Давайте его использовать?

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +        System.out.println("nen");
Нужно либо убрать либо заменить на логгер. Давайте в других местах проверим тоже

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +        if (!LocalDateTime.parse(eventDto.getEventDate(), FORMATTER).isAfter(LocalDateTime.now().minusHours(2))) {
eventDto.getEventDate() может null вернуть?

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +
Лишняя пустая строка

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/resources/schema.sql
> +    name VARCHAR,
Смотрите, общий комментарий по скрипту и модели данных. Вы когда архитектуру БД планируете, нужно продумать размерность полей, то есть, например, поле код не должно иметь стандартный размер в 255, а его можно сделать, например, в 50 символов, а вот для описание нужно больше места, поэтому логичнее под данную колонку выделить, например, 1000. 
Кроме того, после того как Вы все указали в скрипте, тоже самое нужно сделать в аннотации Column для классов моделей. Указать размерность поля, а также дополнительные флаги, например, nullable = false.

2022-11-02 06:55 UTC, Frilock commented on main-service/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Знаю, что по ТЗ у Вас сказано, чтобы в Readme файле была ссылка на проект. Предлагаю также в данном файле разместить информацию о самом проекте, за что каждый модуль отвечает, как проект собирается. Чтобы стороннему человеку который видит Ваш проект было проще. Кроме того, можно описать специфические конфиг файлы, если они есть. Это хорошая практика.

2022-11-02 06:55 UTC, Frilock commented on stats-service/src/main/java/ru/practicum/explore_with_me/mapper/HitMapper.java
> +                .timestamp(hit.getTimestamp().format(FORMATTER))
hit.getTimestamp() null не вернет? будьте аккуратны в таких местах

2022-11-03 13:40 UTC, madromk commented on main-service/src/main/java/ru/practicum/explore_with_me/event/service/EventService.java
> +        if (!LocalDateTime.parse(eventDto.getEventDate(), FORMATTER).isAfter(LocalDateTime.now().minusHours(2))) {
не может, т.к поле eventDate помечено аннотацией notnull

2022-11-03 15:26 UTC, madromk commented on stats-service/src/main/java/ru/practicum/explore_with_me/mapper/HitMapper.java
> +                .timestamp(hit.getTimestamp().format(FORMATTER))
тут не вернёт, потому что поле этого объекта создается как LocalDateTime.now()

2022-11-04 21:39 UTC, Frilock approved these changes
Добрый вечер, работу принял, ошибок не вижу. В дальнейшем советую все таки покрыть слой сервиса unit тестами, так работа будет выглядеть солиднее. Успехов в дальнейшем

2022-11-04 21:39 UTC, Frilock commented on main-service/src/main/java/ru/practicum/explore/client/base/BaseClient.java
> +        ResponseEntity<Object> response;
На мой взгляд, так было бы лучше

try {
            ResponseEntity<Object> response = parameters != null 
                    ? rest.exchange(path, method, requestEntity, Object.class, parameters)
                    : rest.exchange(path, method, requestEntity, Object.class);
            return prepareMainResponse(response);
        } catch (HttpStatusCodeException e) {
            return ResponseEntity.status(e.getStatusCode()).body(e.getResponseBodyAsByteArray());
        }

2022-11-08 15:17 UTC, merged